{
 "title": "Spark Performance",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Successfully completed tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(application_name) (metrics_executor_completedTasks_total{executor_id=\"driver\"})/sum by(application_name) (metrics_executor_totalTasks_total{executor_id=\"driver\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total failed tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(application_name) (metrics_executor_failedTasks_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(application_name) (metrics_executor_activeTasks)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "max(spark_info) by (version, revision)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver Total memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(application_name) (metrics_executor_memoryUsed_bytes{executor_id=\"driver\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver Total Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(application_name) (metrics_executor_totalCores{executor_id=\"driver\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver Total disk used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(application_name) (metrics_executor_diskUsed_bytes{executor_id=\"driver\"})/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(application_name, instance, executor_id) (metrics_executor_memoryUsed_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OnHeapStorageMemory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(application_name, instance, executor_id) (metrics_executor_usedOnHeapStorageMemory_bytes) /sum by(application_name, instance, executor_id) (metrics_executor_totalOnHeapStorageMemory_bytes))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OffHeapStorageMemory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(application_name, instance, executor_id) (metrics_executor_usedOffHeapStorageMemory_bytes) /sum by(application_name, instance, executor_id) (metrics_executor_totalOffHeapStorageMemory_bytes))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Processing Time Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "metrics_MyPySparkStreamingApp_driver_DAGScheduler_messageProcessingTime_95thPercentile",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "metrics_MyPySparkStreamingApp_driver_DAGScheduler_messageProcessingTime_98thPercentile",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "metrics_MyPySparkStreamingApp_driver_DAGScheduler_messageProcessingTime_50thPercentile",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}